# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: prep_env
dependencies:
  - python=3.8.16
  - pandas=1.5.2
  - pip:
    - mlflow
    - azure-ai-ml
    - azureml-fsspec mltable
channels:
  - conda-forge