name: 'MlPipeline'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
    paths:
      - code/train/**
      - infra/**
      - .github/workflows/dataprep.yml
      - cli/setup.sh

jobs:
  prep_and_train:
    name: "DataPrep"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: setup-cli
        run: |
            source "${{ github.workspace }}/infra/sdk_helpers.sh";
            bash setup.sh
        working-directory: cli
        continue-on-error: true
      - name: run job
        run: |
            source "${{ github.workspace }}/infra/sdk_helpers.sh";
            export connection_string = ${{secrets.BLOB_CONNECTION}}
            bash -x run-job.sh dataprep.yml
        working-directory: code/train