name: prepare-env
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.11
  - pip
  - pip:
      - tensorflow-recommenders
      - pandas
      - mlflow
      - azureml-mlflow
      - tensorboard == 2.11.2